### ISSUE TITLE
GSDumpGUI issues

### ISSUE THREAD

**Issue by mirh** [PCSX2/GSDumpGUI#1]
- [x] Closing GSDumpGUI doesn't close the Dump Preview automatically.
- [x] Crash on start when another instance is already open.
- [x] Crash when trying to run a render that the driver/hardware doesn't support (example Opengl HW on Sandy/Ivy Bridge IGPU.
- [x] You have to click two times start/configure buttons before anything happens.
- [x] Renderer Override could be better structured with dx9/dx11/ogl radio buttons and a SW (or hw) checkbox.
- [x] [Try to] auto-fill the two directories text boxes if dumps/gsdx is found in \<GSDumpGUI-root-dir>
- [ ] Wrong registers displaying, or something https://github.com/PCSX2/pcsx2/issues/1929#issuecomment-299490506
- [x] Wrong refresh behaviour [link](https://github.com/PCSX2/pcsx2/issues/1637#issuecomment-257140963)

**Comment by lightningterror** [comment]
Closing as gs debugging has been integrated in to the core, gsdumpgui will be a legacy tool for older versions.
